### ISSUE TITLE
How to start the R22 helicopter?

### ISSUE THREAD

**Issue by tilongzs** [jentron/R22#1]
It works well in Flight Gear. But when I loaded it with JSBSim standalone, I couldn't turn the main rotor and the engine didn't work. In the output CSV table, the output value /rotors/main/rpm is less than 10, and the system/electrical/starter-norm is 0 instead of the 1 I set.
Could you help me modify this batch file? I really don't know what attributes to use. I've been tossing around for a week. The engine starts and the rotor runs steadily. This attachment is what I am using now. It contains batch files and my compiled jsbsim. exe. You can use self-compiled jsbsim. exe instead.
Thanks.

set aircraftname=R22
set resetname=reset00

JSBSim --aircraft=%aircraftname% --initfile=%resetname%^
--outputlogfile=runJSBSim_withAircraft_%aircraftname%.csv --simulation-rate=200 --end=1000^
--property=fcs/throttle-cmd-norm=1.0^
--property=propulsion/magneto_cmd=1^
--property=propulsion/starter_cmd=1^
--property=fcs/left-brake-cmd-norm=0^
--property=fcs/right-brake-cmd-norm=0^
--property=fcs/center-brake-cmd-norm=0^
--property=systems/electrical/starter-norm=1^
--property=/engines/engine/n1=1^

runJSBSim_withAircraft_%aircraftname%.log

pause
[JSBSimConsole.zip](https://github.com/jentron/R22/files/3489549/JSBSimConsole.zip)

**Comment by jentron** [comment]
This model was written as an interactive procedures trainer in FlightGear, so starting it in JSBSim might be a little bit tricky. I would suggest first, instead of a command-line batch file, you use the full XML-scripting capabilities of JSBSim. See http://www.holycows.net/JSBSim_Script_Tutorial.pdf for an example.  

There is a sample script in Resources here that might help

`JSBSim --script=aircraft/R22/Resources/script_runup.xml`
